<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span><ul class="toc-item"><li><span><a href="#Вывод" data-toc-modified-id="Вывод-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Вывод</a></span></li></ul></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span><ul class="toc-item"><li><span><a href="#Вывод" data-toc-modified-id="Вывод-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Вывод</a></span></li></ul></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span><ul class="toc-item"><li><span><a href="#Вывод" data-toc-modified-id="Вывод-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Вывод</a></span></li></ul></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Необходимо разработать такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import make_scorer
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.dummy import DummyClassifier
from sklearn.metrics import r2_score

In [2]:
data = pd.read_csv('/datasets/insurance.csv')

In [3]:
display(data)

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0       1     41.0   49600.0            1                  0
1       0     46.0   38000.0            1                  1
2       0     29.0   21000.0            0                  0
3       0     21.0   41700.0            2                  0
4       1     28.0   26100.0            0                  0
...   ...      ...       ...          ...                ...
4995    0     28.0   35700.0            2                  0
4996    0     34.0   52400.0            1                  0
4997    0     20.0   33900.0            2                  0
4998    1     22.0   32700.0            3                  0
4999    1     28.0   40600.0            1                  0

[5000 rows x 5 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
Пол                  5000 non-null int64
Возраст              5000 non-null float64
Зарплата             5000 non-null float64
Члены семьи          5000 non-null int64
Страховые выплаты    5000 non-null int64
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


In [5]:
data.describe()

Пол      Возраст      Зарплата  Члены семьи  Страховые выплаты
count  5000.000000  5000.000000   5000.000000  5000.000000        5000.000000
mean      0.499000    30.952800  39916.360000     1.194200           0.148000
std       0.500049     8.440807   9900.083569     1.091387           0.463183
min       0.000000    18.000000   5300.000000     0.000000           0.000000
25%       0.000000    24.000000  33300.000000     0.000000           0.000000
50%       0.000000    30.000000  40200.000000     1.000000           0.000000
75%       1.000000    37.000000  46600.000000     2.000000           0.000000
max       1.000000    65.000000  79000.000000     6.000000           5.000000

### Вывод
Представленные данные были изучены, по итогу изучения не было обнаружено аномалий, следовательно изначальные данные были оставлены без изменения

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** Не изменится

**Обоснование:** 
Примем 
$$
a_p = XPw
$$
$$
w_p = P^{-1} w
$$
Тогда
$$
a_p = Xw_p
$$
Применим формулу обучения для матрицы $XP$: 
$$
w_p = ((XP)^T (XP))^{-1} (XP)^T y
$$
Преобразуем:
$$
w_p = (P^T X^T (XP))^{-1} (XP)^T y
$$
$$
w_p = (P^T (X^T X)P))^{-1} (XP)^T y
$$
$$
w_p = P^{-1} (X^T X)^{-1} (P^T)^{-1} P^T X^T y
$$
Сократим:
$$
w_p = P^{-1} (X^T X)^{-1} X^T y
$$
Известно что:
$$
w = (X^T X)^{-1} X^T y
$$
Следовательно 
$$
w_p = P^{-1} w
$$
Тогда
$$
a_p = XPP^{-1} w
$$
$$
a_p = Xw
$$
### Вывод
Можно сделать вывод о том, что $a = a_p$, следовательно в результате заданного умножения качество линейной регрессии не изменится

## Алгоритм преобразования

**Алгоритм**

Умножим на случайно созданную обратимую матрицу, размером 4x4. После этого сравним результаты преобразования метрикой R2_score.

**Обоснование**

По результату теоретического обоснования был сделан вывод о том, что при подобном преобразовании качество линейной регрессии не изменится.

## Проверка алгоритма

In [6]:
P = np.random.normal(0, 20, size=(4, 4))

In [7]:
print(P)

[[  8.37979043  -8.62826227 -19.18407152 -23.85562511]
 [  3.77755253 -13.23844009 -21.12356449  -4.97265758]
 [ 34.39787581  17.51220196  -8.18396953  32.19438797]
 [-20.30016418  10.22935678  12.56441994  -2.28561408]]


In [8]:
print(np.linalg.inv(P)) # рассчитана обратная матрица, следовательно можно сделать вывод о том, что матрица обратимая, в случае ошибки поменять параметры создания случайной матрицы.

[[ 1.67357097e-02 -4.37901376e-02  2.33256533e-03 -4.65485158e-02]
 [ 3.72679965e-02 -5.76970660e-03  3.15332362e-02  6.77422587e-02]
 [-1.07392986e-02 -5.97339089e-02 -2.07887039e-02 -5.07743828e-02]
 [-4.08831390e-02  3.47410702e-02  6.13194411e-03 -2.11854201e-05]]


In [9]:
features = data.drop(['Страховые выплаты'], axis =1)

In [10]:
new_features = features@P

In [11]:
print(new_features)

                 0              1              2             3
0     1.706278e+06  868064.042324 -406797.574552  1.596612e+06
1     1.307273e+06  664864.935636 -311949.961739  1.223156e+06
2     7.224649e+05  367372.326422 -172475.943529  6.759379e+05
3     1.434430e+06  730001.273252 -341689.995473  1.342397e+06
4     8.978987e+05  456689.166601 -214212.248646  8.401104e+05
...            ...            ...            ...           ...
4995  1.228069e+06  624835.392404 -292734.043236  1.149196e+06
4996  1.802557e+06  917199.505158 -429545.640217  1.686815e+06
4997  1.166123e+06  593419.336395 -277833.909564  1.091286e+06
4998  1.124841e+06  572379.818256 -268062.012907  1.052616e+06
4999  1.396648e+06  710626.324395 -332867.242431  1.306927e+06

[5000 rows x 4 columns]


In [12]:
target = data['Страховые выплаты']
features_train, features_valid, target_train, target_valid = train_test_split(features, target, test_size=0.25, random_state=12345)

In [13]:
model = LinearRegression(normalize = False)
model.fit(features_train, target_train)
predictions_valid = model.predict(features_valid)
r2 = r2_score(target_valid, predictions_valid)
print('R2_score модели до преобразования:', r2)

R2_score модели до преобразования: 0.435227571270266


In [14]:
target = data['Страховые выплаты']
new_features_train, new_features_valid, target_train, target_valid = train_test_split(new_features, target, test_size=0.25, random_state=12345)

In [15]:
model = LinearRegression(normalize = False)
model.fit(new_features_train, target_train)
predictions_valid = model.predict(new_features_valid)
r2 = r2_score(target_valid, predictions_valid)
print('R2_score модели после преобразования:', r2)

R2_score модели после преобразования: 0.43522757126935496


### Вывод 
По итогу исследования моделей, выявлено, то что значения параметра r2_score не отличаются, следовательно можно подтвердить вывод теоретического обоснования